M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2026-05-12T03:12:21-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-12T03:12:21-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X52.5Y-104.0
X52.5Y-107.0
T2
X53.5Y-97.0
X53.5Y-127.0
X90.5Y-97.0
X90.5Y-127.0
M30
